
object CountryList  {

  val FullCountryName = Map("a" -> List("Afghanistan", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla", "Antarctica", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan"),
    "b" -> List("Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bonaire", "Bosnia and Herzegovina", "Botswana", "Bouvet Island", "Brazil", "British Indian Ocean Territory", "Brunei Darussalam", "Bulgaria", "Burkina Faso", "Burundi","Brasil"),
    "c" -> List("Cabo Verde", "Cambodia", "Cameroon", "Canada", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Christmas Island", "Cocos", "Colombia", "Comoros", "Congo", "Cook Islands", "Costa Rica", "Croatia", "Cuba", "Curaçao", "Cyprus", "Czechia", "Côte d'Ivoire"),
    "d" -> List("Denmark", "Djibouti", "Dominica", "Dominican Republic","Deutschland"),
    "e" -> List("Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia","England"),
    "f" -> List("Falkland Islands", "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "French Polynesia", "French Southern Territories"),
    "g" -> List("Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea", "Guinea-Bissau", "Guyana"),
    "h" -> List("Haiti", "McDonald Islands", "Holy See", "Honduras", "Hong Kong", "Hungary"),
    "i" -> List("Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Isle of Man", "Israel", "Italy"),
    "j" -> List("Jamaica", "Japan", "Jersey", "Jordan"),
    "k" -> List("Kazakhstan", "Kenya", "Kiribati", "Korea", "Korea", "Kuwait", "Kyrgyzstan"),
    "l" -> List("Lao People's Democratic Republic", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg"),
    "m" -> List("Macao", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia (Federated States of)", "Moldova", "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar"),
    "n" -> List("Namibia", "Nauru", "Nepal", "Netherlands (the)", "New Caledonia", "New Zealand", "Nicaragua", "Niger (the)", "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway"),
    "o" -> List("Oman"),
    "p" -> List("Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn", "Poland", "Portugal", "Puerto Rico"),
    "q" -> List("Qatar"),
    "r" -> List("Republic of North Macedonia", "Romania", "Russian Federation", "Rwanda", "Réunion"),
    "s" -> List("Saint Barthélemy", "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia", "Saint Martin", "Saint Pierre and Miquelon", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Sint Maarten", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Georgia", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Svalbard and Jan Mayen", "Sweden", "Switzerland", "Syrian Arab Republic"),
    "t" -> List("Taiwan", "Tajikistan", "Tanzania, United Republic of", "Thailand", "Timor-Leste", "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Türkiye", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu"),
    "u" -> List("Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States of America", "Uruguay", "Uzbekistan"),
    "v" -> List("Vanuatu", "Venezuela", "Viet Nam", "Virgin Islands", "Virgin Islands"),
    "w" -> List("Wallis and Futuna", "Western Sahara"),
    "y" -> List("Yemen"),
    "z" -> List("Zambia", "Zimbabwe")
  )
  val CountryName2 = Map(
    "AF" -> "Afghanistan",
    "AL" -> "Albania",
    "DZ" -> "Algeria",
    "AS" -> "American Samoa",
    "AD" -> "Andorra",
    "AO" -> "Angola",
    "AI" -> "Anguilla",
    "AQ" -> "Antarctica",
    "AG" -> "Antigua and Barbuda",
    "AR" -> "Argentina",
    "AM" -> "Armenia",
    "AW" -> "Aruba",
    "AU" -> "Australia",
    "AT" -> "Austria",
    "AZ" -> "Azerbaijan",
    "BS" -> "Bahamas",
    "BH" -> "Bahrain",
    "BD" -> "Bangladesh",
    "BB" -> "Barbados",
    "BY" -> "Belarus",
    "BE" -> "Belgium",
    "BZ" -> "Belize",
    "BJ" -> "Benin",
    "BM" -> "Bermuda",
    "BT" -> "Bhutan",
    "BO" -> "Bolivia",
    "BQ" -> "Bonaire, Sint Eustatius and Saba",
    "BA" -> "Bosnia and Herzegovina",
    "BW" -> "Botswana",
    "BV" -> "Bouvet Island",
    "BR" -> "Brazil",
    "IO" -> "British Indian Ocean Territory ",
    "BN" -> "Brunei Darussalam",
    "BG" -> "Bulgaria",
    "BF" -> "Burkina Faso",
    "BI" -> "Burundi",
    "CV" -> "Cabo Verde",
    "KH" -> "Cambodia",
    "CM" -> "Cameroon",
    "CA" -> "Canada",
    "KY" -> "Cayman Islands",
    "CF" -> "Central African Republic",
    "TD" -> "Chad",
    "CL" -> "Chile",
    "CN" -> "China",
    "CX" -> "Christmas Island",
    "CC" -> "Cocos",
    "CO" -> "Colombia",
    "KM" -> "Comoros",
    "CD" -> "Congo",
    "CG" -> "Congo",
    "CK" -> "Cook Islands",
    "CR" -> "Costa Rica",
    "HR" -> "Croatia",
    "CU" -> "Cuba",
    "CW" -> "Curaçao",
    "CY" -> "Cyprus",
    "CZ" -> "Czechia",
    "CI" -> "Côte d'Ivoire",
    "DK" -> "Denmark",
    "DJ" -> "Djibouti",
    "DM" -> "Dominica",
    "DO" -> "Dominican Republic",
    "EC" -> "Ecuador",
    "EG" -> "Egypt",
    "SV" -> "El Salvador",
    "GQ" -> "Equatorial Guinea",
    "ER" -> "Eritrea",
    "EE" -> "Estonia",
    "SZ" -> "Eswatini",
    "ET" -> "Ethiopia",
    "FK" -> "Falkland Islands",
    "FO" -> "Faroe Islands",
    "FJ" -> "Fiji",
    "FI" -> "Finland",
    "FR" -> "France",
    "GF" -> "French Guiana",
    "PF" -> "French Polynesia",
    "TF" -> "French Southern Territories",
    "GA" -> "Gabon",
    "GM" -> "Gambia",
    "GE" -> "Georgia",
    "DE" -> "Germany",
    "GH" -> "Ghana",
    "GI" -> "Gibraltar",
    "GR" -> "Greece",
    "GL" -> "Greenland",
    "GD" -> "Grenada",
    "GP" -> "Guadeloupe",
    "GU" -> "Guam",
    "GT" -> "Guatemala",
    "GG" -> "Guernsey",
    "GN" -> "Guinea",
    "GW" -> "Guinea-Bissau",
    "GY" -> "Guyana",
    "HT" -> "Haiti",
    "HM" -> "Heard Island and McDonald Islands",
    "VA" -> "Holy See",
    "HN" -> "Honduras",
    "HK" -> "Hong Kong",
    "HU" -> "Hungary",
    "IS" -> "Iceland",
    "IN" -> "India",
    "ID" -> "Indonesia",
    "IR" -> "Iran",
    "IQ" -> "Iraq",
    "IE" -> "Ireland",
    "IM" -> "Isle of Man",
    "IL" -> "Israel",
    "IT" -> "Italy",
    "JM" -> "Jamaica",
    "JP" -> "Japan",
    "JE" -> "Jersey",
    "JO" -> "Jordan",
    "KZ" -> "Kazakhstan",
    "KE" -> "Kenya",
    "KI" -> "Kiribati",
    "KP" -> "Korea",
    "KR" -> "Korea",
    "KW" -> "Kuwait",
    "KG" -> "Kyrgyzstan",
    "LA" -> "Lao People's Democratic Republic",
    "LV" -> "Latvia",
    "LB" -> "Lebanon",
    "LS" -> "Lesotho",
    "LR" -> "Liberia",
    "LY" -> "Libya",
    "LI" -> "Liechtenstein",
    "LT" -> "Lithuania",
    "LU" -> "Luxembourg",
    "MO" -> "Macao",
    "MG" -> "Madagascar",
    "MW" -> "Malawi",
    "MY" -> "Malaysia",
    "MV" -> "Maldives",
    "ML" -> "Mali",
    "MT" -> "Malta",
    "MH" -> "Marshall Islands",
    "MQ" -> "Martinique",
    "MR" -> "Mauritania",
    "MU" -> "Mauritius",
    "YT" -> "Mayotte",
    "MX" -> "Mexico",
    "FM" -> "Micronesia",
    "MD" -> "Moldova",
    "MC" -> "Monaco",
    "MN" -> "Mongolia",
    "ME" -> "Montenegro",
    "MS" -> "Montserrat",
    "MA" -> "Morocco",
    "MZ" -> "Mozambique",
    "MM" -> "Myanmar",
    "NA" -> "Namibia",
    "NR" -> "Nauru",
    "NP" -> "Nepal",
    "NL" -> "Netherlands",
    "NC" -> "New Caledonia",
    "NZ" -> "New Zealand",
    "NI" -> "Nicaragua",
    "NE" -> "Niger",
    "NG" -> "Nigeria",
    "NU" -> "Niue",
    "NF" -> "Norfolk Island",
    "MP" -> "Northern Mariana Islands",
    "NO" -> "Norway",
    "OM" -> "Oman",
    "PK" -> "Pakistan",
    "PW" -> "Palau",
    "PS" -> "Palestine, State of",
    "PA" -> "Panama",
    "PG" -> "Papua New Guinea",
    "PY" -> "Paraguay",
    "PE" -> "Peru",
    "PH" -> "Philippines",
    "PN" -> "Pitcairn",
    "PL" -> "Poland",
    "PT" -> "Portugal",
    "PR" -> "Puerto Rico",
    "QA" -> "Qatar",
    "MK" -> "Republic of North Macedonia",
    "RO" -> "Romania",
    "RU" -> "Russian Federation",
    "RW" -> "Rwanda",
    "RE" -> "Réunion",
    "BL" -> "Saint Barthélemy",
    "SH" -> "Saint Helena, Ascension and Tristan da Cunha",
    "KN" -> "Saint Kitts and Nevis",
    "LC" -> "Saint Lucia",
    "MF" -> "Saint Martin",
    "PM" -> "Saint Pierre and Miquelon",
    "VC" -> "Saint Vincent and the Grenadines",
    "WS" -> "Samoa",
    "SM" -> "San Marino",
    "ST" -> "Sao Tome and Principe",
    "SA" -> "Saudi Arabia",
    "SN" -> "Senegal",
    "RS" -> "Serbia",
    "SC" -> "Seychelles",
    "SL" -> "Sierra Leone",
    "SG" -> "Singapore",
    "SX" -> "Sint Maarten",
    "SK" -> "Slovakia",
    "SI" -> "Slovenia",
    "SB" -> "Solomon Islands",
    "SO" -> "Somalia",
    "ZA" -> "South Africa",
    "GS" -> "South Georgia and the South Sandwich Islands",
    "SS" -> "South Sudan",
    "ES" -> "Spain",
    "LK" -> "Sri Lanka",
    "SD" -> "Sudan",
    "SR" -> "Suriname",
    "SJ" -> "Svalbard and Jan Mayen",
    "SE" -> "Sweden",
    "CH" -> "Switzerland",
    "SY" -> "Syrian Arab Republic",
    "TW" -> "Taiwan",
    "TJ" -> "Tajikistan",
    "TZ" -> "Tanzania, United Republic of",
    "TH" -> "Thailand",
    "TL" -> "Timor-Leste",
    "TG" -> "Togo",
    "TK" -> "Tokelau",
    "TO" -> "Tonga",
    "TT" -> "Trinidad and Tobago",
    "TN" -> "Tunisia",
    "TR" -> "Turkey",
    "TM" -> "Turkmenistan",
    "TC" -> "Turks and Caicos Islands",
    "TV" -> "Tuvalu",
    "UG" -> "Uganda",
    "UA" -> "Ukraine",
    "AE" -> "United Arab Emirates",
    "GB" -> "United Kingdom of Great Britain and Northern Ireland",
    "UM" -> "United States Minor Outlying Islands",
    "US" -> "United States of America",
    "UY" -> "Uruguay",
    "UZ" -> "Uzbekistan",
    "VU" -> "Vanuatu",
    "VE" -> "Venezuela",
    "VN" -> "Viet Nam",
    "VG" -> "Virgin Islands",
    "VI" -> "Virgin Islands",
    "WF" -> "Wallis and Futuna",
    "EH" -> "Western Sahara",
    "YE" -> "Yemen",
    "ZM" -> "Zambia",
    "ZW" -> "Zimbabwe",
    "AX" -> "Åland Islands"
  )
  val CountryName3 = Map(
    "AFG" -> "Afghanistan",
    "ALB" -> "Albania",
    "DZA" -> "Algeria",
    "ASM" -> "American Samoa",
    "AND" -> "Andorra",
    "AGO" -> "Angola",
    "AIA" -> "Anguilla",
    "ATA" -> "Antarctica",
    "ATG" -> "Antigua and Barbuda",
    "ARG" -> "Argentina",
    "ARM" -> "Armenia",
    "ABW" -> "Aruba",
    "AUS" -> "Australia",
    "AUT" -> "Austria",
    "AZE" -> "Azerbaijan",
    "BHS" -> "Bahamas ",
    "BHR" -> "Bahrain",
    "BGD" -> "Bangladesh",
    "BRB" -> "Barbados",
    "BLR" -> "Belarus",
    "BEL" -> "Belgium",
    "BLZ" -> "Belize",
    "BEN" -> "Benin",
    "BMU" -> "Bermuda",
    "BTN" -> "Bhutan",
    "BOL" -> "Bolivia",
    "BES" -> "Bonaire, Sint Eustatius and Saba",
    "BIH" -> "Bosnia and Herzegovina",
    "BWA" -> "Botswana",
    "BVT" -> "Bouvet Island",
    "BRA" -> "Brazil",
    "IOT" -> "British Indian Ocean Territory",
    "BRN" -> "Brunei Darussalam",
    "BGR" -> "Bulgaria",
    "BFA" -> "Burkina Faso",
    "BDI" -> "Burundi",
    "CPV" -> "Cabo Verde",
    "KHM" -> "Cambodia",
    "CMR" -> "Cameroon",
    "CAN" -> "Canada",
    "CYM" -> "Cayman Islands",
    "CAF" -> "Central African Republic",
    "TCD" -> "Chad",
    "CHL" -> "Chile",
    "CHN" -> "China",
    "CXR" -> "Christmas Island",
    "CCK" -> "Cocos",
    "COL" -> "Colombia",
    "COM" -> "Comoros",
    "COD" -> "Congo",
    "COG" -> "Congo ",
    "COK" -> "Cook Islands",
    "CRI" -> "Costa Rica",
    "HRV" -> "Croatia",
    "CUB" -> "Cuba",
    "CUW" -> "Curaçao",
    "CYP" -> "Cyprus",
    "CZE" -> "Czechia",
    "CIV" -> "Côte d'Ivoire",
    "DNK" -> "Denmark",
    "DJI" -> "Djibouti",
    "DMA" -> "Dominica",
    "DOM" -> "Dominican Republic",
    "ECU" -> "Ecuador",
    "EGY" -> "Egypt",
    "SLV" -> "El Salvador",
    "GNQ" -> "Equatorial Guinea",
    "ERI" -> "Eritrea",
    "EST" -> "Estonia",
    "SWZ" -> "Eswatini",
    "ETH" -> "Ethiopia",
    "FLK" -> "Falkland Islands",
    "FRO" -> "Faroe Islands",
    "FJI" -> "Fiji",
    "FIN" -> "Finland",
    "FRA" -> "France",
    "GUF" -> "French Guiana",
    "PYF" -> "French Polynesia",
    "ATF" -> "French Southern Territories",
    "GAB" -> "Gabon",
    "GMB" -> "Gambia",
    "GEO" -> "Georgia",
    "DEU" -> "Germany",
    "GHA" -> "Ghana",
    "GIB" -> "Gibraltar",
    "GRC" -> "Greece",
    "GRL" -> "Greenland",
    "GRD" -> "Grenada",
    "GLP" -> "Guadeloupe",
    "GUM" -> "Guam",
    "GTM" -> "Guatemala",
    "GGY" -> "Guernsey",
    "GIN" -> "Guinea",
    "GNB" -> "Guinea-Bissau",
    "GUY" -> "Guyana",
    "HTI" -> "Haiti",
    "HMD" -> "Heard Island and McDonald Islands",
    "VAT" -> "Holy See ",
    "HND" -> "Honduras",
    "HKG" -> "Hong Kong",
    "HUN" -> "Hungary",
    "ISL" -> "Iceland",
    "IND" -> "India",
    "IDN" -> "Indonesia",
    "IRN" -> "Iran",
    "IRQ" -> "Iraq",
    "IRL" -> "Ireland",
    "IMN" -> "Isle of Man",
    "ISR" -> "Israel",
    "ITA" -> "Italy",
    "JAM" -> "Jamaica",
    "JPN" -> "Japan",
    "JEY" -> "Jersey",
    "JOR" -> "Jordan",
    "KAZ" -> "Kazakhstan",
    "KEN" -> "Kenya",
    "KIR" -> "Kiribati",
    "PRK" -> "Korea",
    "KOR" -> "Korea",
    "KWT" -> "Kuwait",
    "KGZ" -> "Kyrgyzstan",
    "LAO" -> "Lao People's Democratic Republic",
    "LVA" -> "Latvia",
    "LBN" -> "Lebanon",
    "LSO" -> "Lesotho",
    "LBR" -> "Liberia",
    "LBY" -> "Libya",
    "LIE" -> "Liechtenstein",
    "LTU" -> "Lithuania",
    "LUX" -> "Luxembourg",
    "MAC" -> "Macao",
    "MDG" -> "Madagascar",
    "MWI" -> "Malawi",
    "MYS" -> "Malaysia",
    "MDV" -> "Maldives",
    "MLI" -> "Mali",
    "MLT" -> "Malta",
    "MHL" -> "Marshall Islands",
    "MTQ" -> "Martinique",
    "MRT" -> "Mauritania",
    "MUS" -> "Mauritius",
    "MYT" -> "Mayotte",
    "MEX" -> "Mexico",
    "FSM" -> "Micronesia",
    "MDA" -> "Moldova",
    "MCO" -> "Monaco",
    "MNG" -> "Mongolia",
    "MNE" -> "Montenegro",
    "MSR" -> "Montserrat",
    "MAR" -> "Morocco",
    "MOZ" -> "Mozambique",
    "MMR" -> "Myanmar",
    "NAM" -> "Namibia",
    "NRU" -> "Nauru",
    "NPL" -> "Nepal",
    "NLD" -> "Netherlands",
    "NCL" -> "New Caledonia",
    "NZL" -> "New Zealand",
    "NIC" -> "Nicaragua",
    "NER" -> "Niger",
    "NGA" -> "Nigeria",
    "NIU" -> "Niue",
    "NFK" -> "Norfolk Island",
    "MNP" -> "Northern Mariana Islands",
    "NOR" -> "Norway",
    "OMN" -> "Oman",
    "PAK" -> "Pakistan",
    "PLW" -> "Palau",
    "PSE" -> "Palestine, State of",
    "PAN" -> "Panama",
    "PNG" -> "Papua New Guinea",
    "PRY" -> "Paraguay",
    "PER" -> "Peru",
    "PHL" -> "Philippines",
    "PCN" -> "Pitcairn",
    "POL" -> "Poland",
    "PRT" -> "Portugal",
    "PRI" -> "Puerto Rico",
    "QAT" -> "Qatar",
    "MKD" -> "Republic of North Macedonia",
    "ROU" -> "Romania",
    "RUS" -> "Russian Federation",
    "RWA" -> "Rwanda",
    "REU" -> "Réunion",
    "BLM" -> "Saint Barthélemy",
    "SHN" -> "Saint Helena, Ascension and Tristan da Cunha",
    "KNA" -> "Saint Kitts and Nevis",
    "LCA" -> "Saint Lucia",
    "MAF" -> "Saint Martin (French part)",
    "SPM" -> "Saint Pierre and Miquelon",
    "VCT" -> "Saint Vincent and the Grenadines",
    "WSM" -> "Samoa",
    "SMR" -> "San Marino",
    "STP" -> "Sao Tome and Principe",
    "SAU" -> "Saudi Arabia",
    "SEN" -> "Senegal",
    "SRB" -> "Serbia",
    "SYC" -> "Seychelles",
    "SLE" -> "Sierra Leone",
    "SGP" -> "Singapore",
    "SXM" -> "Sint Maarten",
    "SVK" -> "Slovakia",
    "SVN" -> "Slovenia",
    "SLB" -> "Solomon Islands",
    "SOM" -> "Somalia",
    "ZAF" -> "South Africa",
    "SGS" -> "South Georgia and the South Sandwich Islands",
    "SSD" -> "South Sudan",
    "ESP" -> "Spain",
    "LKA" -> "Sri Lanka",
    "SDN" -> "Sudan ",
    "SUR" -> "Suriname",
    "SJM" -> "Svalbard and Jan Mayen",
    "SWE" -> "Sweden",
    "CHE" -> "Switzerland",
    "SYR" -> "Syrian Arab Republic",
    "TWN" -> "Taiwan",
    "TJK" -> "Tajikistan",
    "TZA" -> "Tanzania, United Republic of",
    "THA" -> "Thailand",
    "TLS" -> "Timor-Leste",
    "TGO" -> "Togo",
    "TKL" -> "Tokelau",
    "TON" -> "Tonga",
    "TTO" -> "Trinidad and Tobago",
    "TUN" -> "Tunisia",
    "TUR" -> "Turkey",
    "TKM" -> "Turkmenistan",
    "TCA" -> "Turks and Caicos Islands",
    "TUV" -> "Tuvalu",
    "UGA" -> "Uganda",
    "UKR" -> "Ukraine",
    "ARE" -> "United Arab Emirates ",
    "GBR" -> "United Kingdom of Great Britain and Northern Ireland",
    "UMI" -> "United States Minor Outlying Islands",
    "USA" -> "United States of America",
    "URY" -> "Uruguay",
    "UZB" -> "Uzbekistan",
    "VUT" -> "Vanuatu",
    "VEN" -> "Venezuela",
    "VNM" -> "Viet Nam",
    "VGB" -> "Virgin Islands",
    "VIR" -> "Virgin Islands",
    "WLF" -> "Wallis and Futuna",
    "ESH" -> "Western Sahara",
    "YEM" -> "Yemen",
    "ZMB" -> "Zambia",
    "ZWE" -> "Zimbabwe",
    "ALA" -> "Åland Islands"
  )

  val IndiaCities = Set(
    "Achalpur",
    "Achhnera",
    "Adalaj",
    "Adilabad",
    "Adityapur",
    "Adoni",
    "Adoor",
    "Adra",
    "Adyar",
    "Afzalpur",
    "Agartala",
    "Agra",
    "Ahmedabad",
    "Ahmednagar",
    "Aizawl",
    "Ajmer",
    "Akola",
    "Akot",
    "Alappuzha",
    "Aligarh",
    "AlipurdUrban Agglomerationr",
    "Alirajpur",
    "Allahabad",
    "Alwar",
    "Amalapuram",
    "Amalner",
    "Ambejogai",
    "Ambikapur",
    "Amravati",
    "Amreli",
    "Amritsar",
    "Amroha",
    "Anakapalle",
    "Anand",
    "Anantapur",
    "Anantnag",
    "Anjangaon",
    "Anjar",
    "Ankleshwar",
    "Arakkonam",
    "Arambagh",
    "Araria",
    "Arrah",
    "Arsikere",
    "Aruppukkottai",
    "Arvi",
    "Arwal",
    "Asansol",
    "Asarganj",
    "Ashok Nagar",
    "Athni",
    "Attingal",
    "Aurangabad",
    "Aurangabad",
    "Azamgarh",
    "Bagaha",
    "Bageshwar",
    "Bahadurgarh",
    "Baharampur",
    "Bahraich",
    "Balaghat",
    "Balangir",
    "Baleshwar Town",
    "Ballari",
    "Balurghat",
    "Bankura",
    "Bapatla",
    "Baramula",
    "Barbil",
    "Bargarh",
    "Barh",
    "Baripada Town",
    "Barmer",
    "Barnala",
    "Barpeta",
    "Batala",
    "Bathinda",
    "Begusarai",
    "Belagavi",
    "Bellampalle",
    "Belonia",
    "Bengaluru",
    "Bettiah",
    "BhabUrban Agglomeration",
    "Bhadrachalam",
    "Bhadrak",
    "Bhagalpur",
    "Bhainsa",
    "Bharatpur",
    "Bharuch",
    "Bhatapara",
    "Bhavnagar",
    "Bhawanipatna",
    "Bheemunipatnam",
    "Bhilai Nagar",
    "Bhilwara",
    "Bhimavaram",
    "Bhiwandi",
    "Bhiwani",
    "Bhongir",
    "Bhopal",
    "Bhubaneswar",
    "Bhuj",
    "Bikaner",
    "Bilaspur",
    "Bobbili",
    "Bodhan",
    "Bokaro Steel City",
    "Bongaigaon City",
    "Brahmapur",
    "Buxar",
    "Byasanagar",
    "Chaibasa",
    "Chalakudy",
    "Chandausi",
    "Chandigarh",
    "Changanassery",
    "Charkhi Dadri",
    "Chatra",
    "Chennai",
    "Cherthala",
    "Chhapra",
    "Chhapra",
    "Chikkamagaluru",
    "Chilakaluripet",
    "Chirala",
    "Chirkunda",
    "Chirmiri",
    "Chittoor",
    "Chittur-Thathamangalam",
    "Coimbatore",
    "Cuttack",
    "Dalli-Rajhara",
    "Darbhanga",
    "Darjiling",
    "Davanagere",
    "Deesa",
    "Dehradun",
    "Dehri-on-Sone",
    "Delhi",
    "Deoghar",
    "Dhamtari",
    "Dhanbad",
    "Dharmanagar",
    "Dharmavaram",
    "Dhenkanal",
    "Dhoraji",
    "Dhubri",
    "Dhule",
    "Dhuri",
    "Dibrugarh",
    "Dimapur",
    "Diphu",
    "Dumka",
    "Dumraon",
    "Durg",
    "Eluru",
    "English Bazar",
    "Erode",
    "Etawah",
    "Faridabad",
    "Faridkot",
    "Farooqnagar",
    "Fatehabad",
    "Fatehpur Sikri",
    "Fazilka",
    "Firozabad",
    "Firozpur Cantt.",
    "Firozpur",
    "Forbesganj",
    "Gadwal",
    "Gandhinagar",
    "Gangarampur",
    "Ganjbasoda",
    "Gaya",
    "Giridih",
    "Goalpara",
    "Gobichettipalayam",
    "Gobindgarh",
    "Godhra",
    "Gohana",
    "Gokak",
    "Gooty",
    "Gopalganj",
    "Gudivada",
    "Gudur",
    "Gumia",
    "Guntakal",
    "Guntur",
    "Gurdaspur",
    "Gurgaon",
    "Guruvayoor",
    "Guwahati",
    "Gwalior",
    "Habra",
    "Hajipur",
    "Haldwani-cum-Kathgodam",
    "Hansi",
    "Hapur",
    "Hardoi ",
    "Hardwar",
    "Hazaribag",
    "Hindupur",
    "Hisar",
    "Hoshiarpur",
    "Hubli-Dharwad",
    "Hugli-Chinsurah",
    "Hyderabad",
    "Ichalkaranji",
    "Imphal",
    "Indore",
    "Itarsi",
    "Jabalpur",
    "Jagdalpur",
    "Jaggaiahpet",
    "Jagraon",
    "Jagtial",
    "Jaipur",
    "Jalandhar Cantt.",
    "Jalandhar",
    "Jalpaiguri",
    "Jamalpur",
    "Jammalamadugu",
    "Jammu",
    "Jamnagar",
    "Jamshedpur",
    "Jamui",
    "Jangaon",
    "Jatani",
    "Jehanabad",
    "Jhansi",
    "Jhargram",
    "Jharsuguda",
    "Jhumri Tilaiya",
    "Jind",
    "Jodhpur",
    "Jorhat",
    "Kadapa",
    "Kadi",
    "Kadiri",
    "Kagaznagar",
    "Kailasahar",
    "Kaithal",
    "Kakinada",
    "Kalimpong",
    "Kalpi",
    "Kalyan-Dombivali",
    "Kamareddy",
    "Kancheepuram",
    "Kandukur",
    "Kanhangad",
    "Kannur",
    "Kanpur",
    "Kapadvanj",
    "Kapurthala",
    "Karaikal",
    "Karimganj",
    "Karimnagar",
    "Karjat",
    "Karnal",
    "Karur",
    "Karwar",
    "Kasaragod",
    "Kashipur",
    "KathUrban Agglomeration",
    "Katihar",
    "Kavali",
    "Kayamkulam",
    "Kendrapara",
    "Kendujhar",
    "Keshod",
    "Khair",
    "Khambhat",
    "Khammam",
    "Khanna",
    "Kharagpur",
    "Kharar",
    "Khowai",
    "Kishanganj",
    "Kochi",
    "Kodungallur",
    "Kohima",
    "Kolar",
    "Kolkata",
    "Kollam",
    "Koratla",
    "Korba",
    "Kot Kapura",
    "Kota",
    "Kothagudem",
    "Kottayam",
    "Kovvur",
    "Koyilandy",
    "Kozhikode",
    "Kunnamkulam",
    "Kurnool",
    "Kyathampalle",
    "Lachhmangarh",
    "Ladnu",
    "Ladwa",
    "Lahar",
    "Laharpur",
    "Lakheri",
    "Lakhimpur",
    "Lakhisarai",
    "Lakshmeshwar",
    "Lal Gopalganj Nindaura",
    "Lalganj",
    "Lalganj",
    "Lalgudi",
    "Lalitpur",
    "Lalsot",
    "Lanka",
    "Lar",
    "Lathi",
    "Latur",
    "Lilong",
    "Limbdi",
    "Lingsugur",
    "Loha",
    "Lohardaga",
    "Lonar",
    "Lonavla",
    "Longowal",
    "Loni",
    "Losal",
    "Lucknow",
    "Ludhiana",
    "Lumding",
    "Lunawada",
    "Lunglei",
    "Macherla",
    "Machilipatnam",
    "Madanapalle",
    "Maddur",
    "Madhepura",
    "Madhubani",
    "Madhugiri",
    "Madhupur",
    "Madikeri",
    "Madurai",
    "Magadi",
    "Mahad",
    "Mahalingapura",
    "Maharajganj",
    "Maharajpur",
    "Mahasamund",
    "Mahbubnagar",
    "Mahe",
    "Mahemdabad",
    "Mahendragarh",
    "Mahesana",
    "Mahidpur",
    "Mahnar Bazar",
    "Mahuva",
    "Maihar",
    "Mainaguri",
    "Makhdumpur",
    "Makrana",
    "Malaj Khand",
    "Malappuram",
    "Malavalli",
    "Malda",
    "Malegaon",
    "Malerkotla",
    "Malkangiri",
    "Malkapur",
    "Malout",
    "Malpura",
    "Malur",
    "Manachanallur",
    "Manasa",
    "Manavadar",
    "Manawar",
    "Mancherial",
    "Mandalgarh",
    "Mandamarri",
    "Mandapeta",
    "Mandawa",
    "Mandi Dabwali",
    "Mandi",
    "Mandideep",
    "Mandla",
    "Mandsaur",
    "Mandvi",
    "Mandya",
    "Manendragarh",
    "Maner",
    "Mangaldoi",
    "Mangaluru",
    "Mangalvedhe",
    "Manglaur",
    "Mangrol",
    "Mangrol",
    "Mangrulpir",
    "Manihari",
    "Manjlegaon",
    "Mankachar",
    "Manmad",
    "Mansa",
    "Mansa",
    "Manuguru",
    "Manvi",
    "Manwath",
    "Mapusa",
    "Margao",
    "Margherita",
    "Marhaura",
    "Mariani",
    "Marigaon",
    "Markapur",
    "Marmagao",
    "Masaurhi",
    "Mathabhanga",
    "Mathura",
    "Mattannur",
    "Mauganj",
    "Mavelikkara",
    "Mavoor",
    "Mayang Imphal",
    "Medak",
    "Medininagar (Daltonganj)",
    "Medinipur",
    "Meerut",
    "Mehkar",
    "Memari",
    "Merta City",
    "Mhaswad",
    "Mhow Cantonment",
    "Mhowgaon",
    "Mihijam",
    "Mira-Bhayandar",
    "Mirganj",
    "Miryalaguda",
    "Modasa",
    "Modinagar",
    "Moga",
    "Mohali",
    "Mokameh",
    "Mokokchung",
    "Monoharpur",
    "Moradabad",
    "Morena",
    "Morinda, India",
    "Morshi",
    "Morvi",
    "Motihari",
    "Motipur",
    "Mount Abu",
    "Mudabidri",
    "Mudalagi",
    "Muddebihal",
    "Mudhol",
    "Mukerian",
    "Mukhed",
    "Muktsar",
    "Mul",
    "Mulbagal",
    "Multai",
    "Mumbai",
    "Mundargi",
    "Mundi",
    "Mungeli",
    "Munger",
    "Murliganj",
    "Murshidabad",
    "Murtijapur",
    "Murwara (Katni)",
    "Musabani",
    "Mussoorie",
    "Muvattupuzha",
    "Muzaffarpur",
    "Mysore",
    "Nabadwip",
    "Nabarangapur",
    "Nabha",
    "Nadbai",
    "Nadiad",
    "Nagaon",
    "Nagapattinam",
    "Nagar",
    "Nagari",
    "Nagarkurnool",
    "Nagaur",
    "Nagda",
    "Nagercoil",
    "Nagina",
    "Nagla",
    "Nagpur",
    "Nahan",
    "Naharlagun",
    "Naidupet",
    "Naihati",
    "Naila Janjgir",
    "Nainital",
    "Nainpur",
    "Najibabad",
    "Nakodar",
    "Nakur",
    "Nalbari",
    "Namagiripettai",
    "Namakkal",
    "Nanded-Waghala",
    "Nandgaon",
    "Nandivaram-Guduvancheri",
    "Nandura",
    "Nandurbar",
    "Nandyal",
    "Nangal",
    "Nanjangud",
    "Nanjikottai",
    "Nanpara",
    "Narasapuram",
    "Narasaraopet",
    "Naraura",
    "Narayanpet",
    "Nargund",
    "Narkatiaganj",
    "Narkhed",
    "Narnaul",
    "Narsinghgarh",
    "Narsinghgarh",
    "Narsipatnam",
    "Narwana",
    "Nashik",
    "Nasirabad",
    "Natham",
    "Nathdwara",
    "Naugachhia",
    "Naugawan Sadat",
    "Nautanwa",
    "Navalgund",
    "Navsari",
    "Nawabganj",
    "Nawada",
    "Nawanshahr",
    "Nawapur",
    "Nedumangad",
    "Neem-Ka-Thana",
    "Neemuch",
    "Nehtaur",
    "Nelamangala",
    "Nellikuppam",
    "Nellore",
    "Nepanagar",
    "New Delhi",
    "Neyveli (TS)",
    "Neyyattinkara",
    "Nidadavole",
    "Nilambur",
    "Nilanga",
    "Nimbahera",
    "Nirmal",
    "Niwai",
    "Niwari",
    "Nizamabad",
    "Nohar",
    "Noida",
    "Nokha",
    "Nokha",
    "Nongstoin",
    "Noorpur",
    "North Lakhimpur",
    "Nowgong",
    "Nowrozabad (Khodargama)",
    "Nuzvid",
    "O' Valley",
    "Obra",
    "Oddanchatram",
    "Ongole",
    "Orai",
    "Osmanabad",
    "Ottappalam",
    "Ozar",
    "P.N.Patti",
    "Pachora",
    "Pachore",
    "Pacode",
    "Padmanabhapuram",
    "Padra",
    "Padrauna",
    "Paithan",
    "Pakaur",
    "Palacole",
    "Palai",
    "Palakkad",
    "Palampur",
    "Palani",
    "Palanpur",
    "Palasa Kasibugga",
    "Palghar",
    "Pali",
    "Pali",
    "Palia Kalan",
    "Palitana",
    "Palladam",
    "Pallapatti",
    "Pallikonda",
    "Palwal",
    "Palwancha",
    "Panagar",
    "Panagudi",
    "Panaji",
    "Panamattom",
    "Panchkula",
    "Panchla",
    "Pandharkaoda",
    "Pandharpur",
    "Pandhurna",
    "PandUrban Agglomeration",
    "Panipat",
    "Panna",
    "Panniyannur",
    "Panruti",
    "Panvel",
    "Pappinisseri",
    "Paradip",
    "Paramakudi",
    "Parangipettai",
    "Parasi",
    "Paravoor",
    "Parbhani",
    "Pardi",
    "Parlakhemundi",
    "Parli",
    "Partur",
    "Parvathipuram",
    "Pasan",
    "Paschim Punropara",
    "Pasighat",
    "Patan",
    "Pathanamthitta",
    "Pathankot",
    "Pathardi",
    "Pathri",
    "Patiala",
    "Patna",
    "Patratu",
    "Pattamundai",
    "Patti",
    "Pattran",
    "Pattukkottai",
    "Patur",
    "Pauni",
    "Pauri",
    "Pavagada",
    "Pedana",
    "Peddapuram",
    "Pehowa",
    "Pen",
    "Perambalur",
    "Peravurani",
    "Peringathur",
    "Perinthalmanna",
    "Periyakulam",
    "Periyasemur",
    "Pernampattu",
    "Perumbavoor",
    "Petlad",
    "Phagwara",
    "Phalodi",
    "Phaltan",
    "Phillaur",
    "Phulabani",
    "Phulera",
    "Phulpur",
    "Phusro",
    "Pihani",
    "Pilani",
    "Pilibanga",
    "Pilibhit",
    "Pilkhuwa",
    "Pindwara",
    "Pinjore",
    "Pipar City",
    "Pipariya",
    "Piriyapatna",
    "Piro",
    "Pithampur",
    "Pithapuram",
    "Pithoragarh",
    "Pollachi",
    "Polur",
    "Pondicherry",
    "Ponnani",
    "Ponneri",
    "Ponnur",
    "Porbandar",
    "Porsa",
    "Port Blair",
    "Powayan",
    "Prantij",
    "Pratapgarh",
    "Pratapgarh",
    "Prithvipur",
    "Proddatur",
    "Pudukkottai",
    "Pudupattinam",
    "Pukhrayan",
    "Pulgaon",
    "Puliyankudi",
    "Punalur",
    "Punch",
    "Pune",
    "Punganur",
    "Punjaipugalur",
    "Puranpur",
    "Puri",
    "Purna",
    "Purnia",
    "PurqUrban Agglomerationzi",
    "Purulia",
    "Purwa",
    "Pusad",
    "Puthuppally",
    "Puttur",
    "Puttur",
    "Qadian",
    "Raayachuru",
    "Rabkavi Banhatti",
    "Radhanpur",
    "Rae Bareli",
    "Rafiganj",
    "Raghogarh-Vijaypur",
    "Raghunathganj",
    "Raghunathpur",
    "Rahatgarh",
    "Rahuri",
    "Raiganj",
    "Raigarh",
    "Raikot",
    "Raipur",
    "Rairangpur",
    "Raisen",
    "Raisinghnagar",
    "Rajagangapur",
    "Rajahmundry",
    "Rajakhera",
    "Rajaldesar",
    "Rajam",
    "Rajampet",
    "Rajapalayam",
    "Rajauri",
    "Rajgarh",
    "Rajgarh",
    "Rajgarh",
    "Rajgir",
    "Rajkot",
    "Rajnandgaon",
    "Rajpipla",
    "Rajpura",
    "Rajsamand",
    "Rajula",
    "Rajura",
    "Ramachandrapuram",
    "Ramagundam",
    "Ramanagaram",
    "Ramanathapuram",
    "Ramdurg",
    "Rameshwaram",
    "Ramganj Mandi",
    "Ramgarh",
    "Ramnagar",
    "Ramnagar",
    "Ramngarh",
    "Rampur Maniharan",
    "Rampur",
    "Rampura Phul",
    "Rampurhat",
    "Ramtek",
    "Ranaghat",
    "Ranavav",
    "Ranchi",
    "Ranebennuru",
    "Rangia",
    "Rania",
    "Ranibennur",
    "Ranipet",
    "Rapar",
    "Rasipuram",
    "Rasra",
    "Ratangarh",
    "Rath",
    "Ratia",
    "Ratlam",
    "Ratnagiri",
    "Rau",
    "Raurkela",
    "Raver",
    "Rawatbhata",
    "Rawatsar",
    "Raxaul Bazar",
    "Rayachoti",
    "Rayadurg",
    "Rayagada",
    "Reengus",
    "Rehli",
    "Renigunta",
    "Renukoot",
    "Reoti",
    "Repalle",
    "Revelganj",
    "Rewa",
    "Rewari",
    "Rishikesh",
    "Risod",
    "Robertsganj",
    "Robertson Pet",
    "Rohtak",
    "Ron",
    "Roorkee",
    "Rosera",
    "Rudauli",
    "Rudrapur",
    "Rudrapur",
    "Rupnagar",
    "Sabalgarh",
    "Sadabad",
    "Sadalagi",
    "Sadasivpet",
    "Sadri",
    "Sadulpur",
    "Sadulshahar",
    "Safidon",
    "Safipur",
    "Sagar",
    "Sagara",
    "Sagwara",
    "Saharanpur",
    "Saharsa",
    "Sahaspur",
    "Sahaswan",
    "Sahawar",
    "Sahibganj",
    "Sahjanwa",
    "Saidpur",
    "Saiha",
    "Sailu",
    "Sainthia",
    "Sakaleshapura",
    "Sakti",
    "Salaya",
    "Salem",
    "Salur",
    "Samalkha",
    "Samalkot",
    "Samana",
    "Samastipur",
    "Sambalpur",
    "Sambhal",
    "Sambhar",
    "Samdhan",
    "Samthar",
    "Sanand",
    "Sanawad",
    "Sanchore",
    "Sandi",
    "Sandila",
    "Sanduru",
    "Sangamner",
    "Sangareddy",
    "Sangaria",
    "Sangli",
    "Sangole",
    "Sangrur",
    "Sankarankovil",
    "Sankari",
    "Sankeshwara",
    "Santipur",
    "Sarangpur",
    "Sardarshahar",
    "Sardhana",
    "Sarni",
    "Sarsod",
    "Sasaram",
    "Sasvad",
    "Satana",
    "Satara",
    "Sathyamangalam",
    "Satna",
    "Sattenapalle",
    "Sattur",
    "Saunda",
    "Saundatti-Yellamma",
    "Sausar",
    "Savanur",
    "Savarkundla",
    "Savner",
    "Sawai Madhopur",
    "Sawantwadi",
    "Sedam",
    "Sehore",
    "Sendhwa",
    "Seohara",
    "Seoni",
    "Seoni-Malwa",
    "Shahabad",
    "Shahabad, Hardoi",
    "Shahabad, Rampur",
    "Shahade",
    "Shahbad",
    "Shahdol",
    "Shahganj",
    "Shahjahanpur",
    "Shahpur",
    "Shahpura",
    "Shahpura",
    "Shajapur",
    "Shamgarh",
    "Shamli",
    "Shamsabad, Agra",
    "Shamsabad, Farrukhabad",
    "Shegaon",
    "Sheikhpura",
    "Shendurjana",
    "Shenkottai",
    "Sheoganj",
    "Sheohar",
    "Sheopur",
    "Sherghati",
    "Sherkot",
    "Shiggaon",
    "Shikaripur",
    "Shikarpur, Bulandshahr",
    "Shikohabad",
    "Shillong",
    "Shimla",
    "Shirdi",
    "Shirpur-Warwade",
    "Shirur",
    "Shishgarh",
    "Shivamogga",
    "Shivpuri",
    "Sholavandan",
    "Sholingur",
    "Shoranur",
    "Shrigonda",
    "Shrirampur",
    "Shrirangapattana",
    "Shujalpur",
    "Siana",
    "Sibsagar",
    "Siddipet",
    "Sidhi",
    "Sidhpur",
    "Sidlaghatta",
    "Sihor",
    "Sihora",
    "Sikanderpur",
    "Sikandra Rao",
    "Sikandrabad",
    "Sikar",
    "Silao",
    "Silapathar",
    "Silchar",
    "Siliguri",
    "Sillod",
    "Silvassa",
    "Simdega",
    "Sindagi",
    "Sindhagi",
    "Sindhnur",
    "Singrauli",
    "Sinnar",
    "Sira",
    "Sircilla",
    "Sirhind Fatehgarh Sahib",
    "Sirkali",
    "Sirohi",
    "Sironj",
    "Sirsa",
    "Sirsaganj",
    "Sirsi",
    "Sirsi",
    "Siruguppa",
    "Sitamarhi",
    "Sitapur",
    "Sitarganj",
    "Sivaganga",
    "Sivagiri",
    "Sivakasi",
    "Siwan",
    "Sohagpur",
    "Sohna",
    "Sojat",
    "Solan",
    "Solapur",
    "Sonamukhi",
    "Sonepur",
    "Songadh",
    "Sonipat",
    "Sopore",
    "Soro",
    "Soron",
    "Soyagaon",
    "Sri Madhopur",
    "Srikakulam",
    "Srikalahasti",
    "Srinagar",
    "Srinagar",
    "Srinivaspur",
    "Srirampore",
    "Srisailam Project (Right Flank Colony) Township",
    "Srivilliputhur",
    "Sugauli",
    "Sujangarh",
    "Sujanpur",
    "Sullurpeta",
    "Sultanganj",
    "Sultanpur",
    "Sumerpur",
    "Sumerpur",
    "Sunabeda",
    "Sunam",
    "Sundargarh",
    "Sundarnagar",
    "Supaul",
    "Surandai",
    "Surapura",
    "Surat",
    "Suratgarh",
    "SUrban Agglomerationr",
    "Thanesar",
    "Thangadh",
    "Thanjavur",
    "Tharad",
    "Tharamangalam",
    "Tharangambadi",
    "Theni Allinagaram",
    "Thirumangalam",
    "Thirupuvanam",
    "Thiruthuraipoondi",
    "Thiruvalla",
    "Thiruvallur",
    "Thiruvananthapuram",
    "Thiruvarur",
    "Thodupuzha",
    "Thoubal",
    "Thrissur",
    "Thuraiyur",
    "Tikamgarh",
    "Tilda Newra",
    "Tilhar",
    "Tindivanam",
    "Tinsukia",
    "Tiptur",
    "Tirora",
    "Tiruchendur",
    "Tiruchengode",
    "Tiruchirappalli",
    "Tirukalukundram",
    "Tirukkoyilur",
    "Tirunelveli",
    "Tirupathur",
    "Tirupathur",
    "Tirupati",
    "Tiruppur",
    "Tirur",
    "Tiruttani",
    "Tiruvannamalai",
    "Tiruvethipuram",
    "Tiruvuru",
    "Tirwaganj",
    "Titlagarh",
    "Tittakudi",
    "Todabhim",
    "Todaraisingh",
    "Tohana",
    "Tonk",
    "Tuensang",
    "Tuljapur",
    "Tulsipur",
    "Tumkur",
    "Tumsar",
    "Tundla",
    "Tuni",
    "Tura",
    "Uchgaon",
    "Udaipur",
    "Udaipur",
    "Udaipurwati",
    "Udgir",
    "Udhagamandalam",
    "Udhampur",
    "Udumalaipettai",
    "Udupi",
    "Ujhani",
    "Ujjain",
    "Unnao",
    "Upleta",
    "Uran Islampur",
    "Uran",
    "Vadipatti",
    "Vadnagar",
    "Vadodara",
    "Vaijapur",
    "Vaikom",
    "Valparai",
    "Valsad",
    "Vandavasi",
    "Vaniyambadi",
    "Vapi",
    "Vapi",
    "Varanasi",
    "Varkala",
    "Vasai-Virar",
    "Vatakara",
    "Vedaranyam",
    "Vellakoil",
    "Vellore",
    "Venkatagiri",
    "Veraval",
    "Vidisha",
    "Vijainagar, Ajmer",
    "Vijapur",
    "Vijayapura",
    "Vijayawada",
    "Vijaypur",
    "Vikarabad",
    "Vikramasingapuram",
    "Viluppuram",
    "Vinukonda",
    "Viramgam",
    "Virudhachalam",
    "Virudhunagar",
    "Visakhapatnam",
    "Visnagar",
    "Viswanatham",
    "Vita",
    "Vizianagaram",
    "Vrindavan",
    "Vyara",
    "Wadgaon Road",
    "Wadhwan",
    "Wadi",
    "Wai",
    "Wanaparthy",
    "Wani",
    "Wankaner",
    "Wara Seoni",
    "Warangal",
    "Wardha",
    "Warhapur",
    "Warisaliganj",
    "Warora",
    "Warud",
    "Washim",
    "Wokha",
    "Yadgir",
    "Yamunanagar",
    "Yanam",
    "Yavatmal",
    "Yawal",
    "Yellandu",
    "Yemmiganur",
    "Yerraguntla",
    "Yevla",
    "Zaidpur",
    "Zamania",
    "Zira",
    "Zirakpur",
    "Zunheboto")
  val IndiaStates = Set("Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal")
  val SpainCities = Set(
    "Madrid",
    "Barcelona",
    "Sevilla",
    "Bilbao",
    "Valencia",
    "Zaragoza",
    "Málaga",
    "Murcia",
    "Granada",
    "Vigo",
    "Palma",
    "A Coruña",
    "Santa María de Gracia",
    "Gijón",
    "Valladolid",
    "Córdoba",
    "Alicante",
    "Cádiz",
    "Pamplona",
    "Oviedo",
    "Zuazo de Vitoria",
    "Santander",
    "Cartagena",
    "Marbella",
    "Mataró",
    "Almería",
    "Burgos",
    "Salamanca",
    "Albacete",
    "Huelva",
    "Logroño",
    "Badajoz",
    "León",
    "Tarragona",
    "Ourense",
    "Jaén",
    "Algeciras",
    "Santiago de Compostela",
    "Lorca",
    "Toledo",
    "Guadalajara",
    "Linares",
    "Arrecife",
    "Mérida",
    "Las Palmas de Gran Canaria",
    "Vitoria-Gasteiz",
    "Castellón de la Plana",
    "Palencia",
    "Lleida",
    "Cáceres",
    "Segovia",
    "Pontevedra",
    "Santa Cruz de Tenerife",
    "Soria",
    "Huesca",
    "Donostia",
    "Cuenca",
    "Girona",
    "Ávila",
    "Ciudad Real",
    "Zamora",
    "Lugo",
    "Teruel"
  )
  val ItalyCities = Set("Venice",
    "Verona",
    "Messina",
    "Padua",
    "Brescia",
    "Taranto",
    "Parma",
    "Prato",
    "Modena",
    "Perugia",
    "Livorno",
    "Ravenna",
    "Foggia",
    "Rimini",
    "Salerno",
    "Ferrara",
    "Sassari",
    "Monza",
    "Bergamo",
    "Pescara",
    "Vicenza",
    "Terni",
    "Novara",
    "Piacenza",
    "Ancona",
    "Arezzo",
    "Cesena",
    "Lecce",
    "Pesaro",
    "Barletta",
    "Alessandria",
    "Pistoia",
    "Pisa",
    "Catanzaro",
    "Lucca",
    "Brindisi",
    "Treviso",
    "Como",
    "Marsala",
    "Grosseto",
    "Pozzuoli",
    "Varese",
    "Fiumicino",
    "Casoria",
    "Asti",
    "Caserta",
    "Gela",
    "Pavia",
    "Cremona",
    "Altamura",
    "Imola",
    "L'AquilaL’Aquila",
    "Massa",
    "Trapani",
    "Viterbo",
    "Cosenza",
    "Potenza",
    "Afragola",
    "Crotone",
    "Pomezia",
    "Vigevano",
    "Carrara",
    "Caltanissetta",
    "Viareggio",
    "Fano",
    "Savona",
    "Matera",
    "Olbia",
    "Legnano",
    "Acerra",
    "Benevento",
    "Agrigento",
    "Faenza",
    "Cerignola",
    "Moncalieri",
    "Foligno",
    "Manfredonia",
    "Cuneo",
    "Trani",
    "Bisceglie",
    "Bitonto",
    "Bagheria",
    "Anzio",
    "Portici",
    "Modica",
    "Sanremo",
    "Avellino",
    "Teramo",
    "Montesilvano",
    "Siena",
    "Gallarate",
    "Velletri",
    "Aversa",
    "Ercolano",
    "Civitavecchia",
    "Acireale",
    "Rovigo",
    "Battipaglia",
    "Chieti",
    "Scafati",
    "Scandicci"
  )
  val USACities = Set(
    "New York",
    "Buffalo",
    "Rochester",
    "Yonkers",
    "Syracuse",
    "Albany",
    "New Rochelle",
    "Mount Vernon",
    "Schenectady",
    "Utica",
    "White Plains",
    "Hempstead",
    "Troy",
    "Niagara Falls",
    "Binghamton",
    "Freeport",
    "Valley Stream",
    "Los Angeles",
    "San Diego",
    "San Jose",
    "San Francisco",
    "Fresno",
    "Sacramento",
    "Long Beach",
    "Oakland",
    "Bakersfield",
    "Anaheim",
    "Santa Ana",
    "Riverside",
    "Stockton",
    "Chula Vista",
    "Irvine",
    "Fremont",
    "San Bernardino",
    "Modesto",
    "Fontana",
    "Oxnard",
    "Moreno Valley",
    "Huntington Beach",
    "Glendale",
    "Santa Clarita",
    "Garden Grove",
    "Oceanside",
    "Rancho Cucamonga",
    "Santa Rosa",
    "Ontario",
    "Lancaster",
    "Elk Grove",
    "Corona",
    "Palmdale",
    "Salinas",
    "Pomona",
    "Hayward",
    "Escondido",
    "Torrance",
    "Sunnyvale",
    "Orange",
    "Fullerton",
    "Pasadena",
    "Thousand Oaks",
    "Visalia",
    "Simi Valley",
    "Concord",
    "Roseville",
    "Victorville",
    "Santa Clara",
    "Vallejo",
    "Berkeley",
    "El Monte",
    "Downey",
    "Costa Mesa",
    "Inglewood",
    "Carlsbad",
    "San Buenaventura (Ventura)",
    "Fairfield",
    "West Covina",
    "Murrieta",
    "Richmond",
    "Norwalk",
    "Antioch",
    "Temecula",
    "Burbank",
    "Daly City",
    "Rialto",
    "Santa Maria",
    "El Cajon",
    "San Mateo",
    "Clovis",
    "Compton",
    "Jurupa Valley",
    "Vista",
    "South Gate",
    "Mission Viejo",
    "Vacaville",
    "Carson",
    "Hesperia",
    "Santa Monica",
    "Westminster",
    "Redding",
    "Santa Barbara",
    "Chico",
    "Newport Beach",
    "San Leandro",
    "San Marcos",
    "Whittier",
    "Hawthorne",
    "Citrus Heights",
    "Tracy",
    "Alhambra",
    "Livermore",
    "Buena Park",
    "Menifee",
    "Diamond Bar",
    "Woodland",
    "Santee",
    "Lake Elsinore",
    "Porterville",
    "Paramount",
    "Eastvale",
    "Rosemead",
    "Hanford",
    "Highland",
    "Brentwood",
    "Novato",
    "Colton",
    "Cathedral City",
    "Delano",
    "Yucaipa",
    "Watsonville",
    "Placentia",
    "Glendora",
    "Gilroy",
    "Palm Desert",
    "Cerritos",
    "West Sacramento",
    "Aliso Viejo",
    "Poway",
    "La Mirada",
    "Rancho Santa Margarita",
    "Cypress",
    "Dublin",
    "Covina",
    "Azusa",
    "Palm Springs",
    "San Luis Obispo",
    "Ceres",
    "San Jacinto",
    "Lincoln",
    "Newark",
    "Lompoc",
    "El Centro",
    "Danville",
    "Bell Gardens",
    "Coachella",
    "Rancho Palos Verdes",
    "San Bruno",
    "Rohnert Park",
    "Brea",
    "La Puente",
    "Campbell",
    "San Gabriel",
    "Beaumont",
    "Morgan Hill",
    "Culver City",
    "Calexico",
    "Stanton",
    "La Quinta",
    "Pacifica",
    "Montclair",
    "Oakley",
    "Monrovia",
    "Los Banos",
    "Martinez",
    "Chicago",
    "Aurora",
    "Rockford",
    "Joliet",
    "Naperville",
    "Springfield",
    "Peoria",
    "Elgin",
    "Waukegan",
    "Cicero",
    "Champaign",
    "Bloomington",
    "Arlington Heights",
    "Evanston",
    "Decatur",
    "Schaumburg",
    "Bolingbrook",
    "Palatine",
    "Skokie",
    "Des Plaines",
    "Orland Park",
    "Tinley Park",
    "Oak Lawn",
    "Berwyn",
    "Mount Prospect",
    "Normal",
    "Wheaton",
    "Hoffman Estates",
    "Oak Park",
    "Downers Grove",
    "Elmhurst",
    "Glenview",
    "DeKalb",
    "Lombard",
    "Belleville",
    "Moline",
    "Buffalo Grove",
    "Bartlett",
    "Urbana",
    "Quincy",
    "Crystal Lake",
    "Plainfield",
    "Streamwood",
    "Carol Stream",
    "Romeoville",
    "Rock Island",
    "Hanover Park",
    "Carpentersville",
    "Wheeling",
    "Park Ridge",
    "Addison",
    "Calumet City",
    "Houston",
    "San Antonio",
    "Dallas",
    "Austin",
    "Fort Worth",
    "El Paso",
    "Arlington",
    "Corpus Christi",
    "Plano",
    "Laredo",
    "Lubbock",
    "Garland",
    "Irving",
    "Amarillo",
    "Grand Prairie",
    "Brownsville",
    "Pasadena",
    "McKinney",
    "Mesquite",
    "McAllen",
    "Killeen",
    "Frisco",
    "Waco",
    "Carrollton",
    "Denton",
    "Midland",
    "Abilene",
    "Beaumont",
    "Round Rock",
    "Odessa",
    "Wichita Falls",
    "Richardson",
    "Lewisville",
    "Tyler",
    "College Station",
    "Pearland",
    "San Angelo",
    "Allen",
    "League City",
    "Sugar Land",
    "Longview",
    "Edinburg",
    "Mission",
    "Bryan",
    "Baytown",
    "Pharr",
    "Temple",
    "Missouri City",
    "Flower Mound",
    "Harlingen",
    "North Richland Hills",
    "Victoria",
    "Conroe",
    "New Braunfels",
    "Mansfield",
    "Cedar Park",
    "Rowlett",
    "Port Arthur",
    "Euless",
    "Georgetown",
    "Pflugerville",
    "DeSoto",
    "San Marcos",
    "Grapevine",
    "Bedford",
    "Galveston",
    "Cedar Hill",
    "Texas City",
    "Wylie",
    "Haltom City",
    "Keller",
    "Coppell",
    "Rockwall",
    "Huntsville",
    "Duncanville",
    "Sherman",
    "The Colony",
    "Burleson",
    "Hurst",
    "Lancaster",
    "Texarkana",
    "Friendswood",
    "Weslaco",
    "Philadelphia",
    "Pittsburgh",
    "Allentown",
    "Erie",
    "Reading",
    "Scranton",
    "Bethlehem",
    "Lancaster",
    "Harrisburg",
    "Altoona",
    "York",
    "State College",
    "Wilkes-Barre",
    "Phoenix",
    "Tucson",
    "Mesa",
    "Chandler",
    "Glendale",
    "Scottsdale",
    "Gilbert",
    "Tempe",
    "Peoria",
    "Surprise",
    "Yuma",
    "Avondale",
    "Goodyear",
    "Flagstaff",
    "Buckeye",
    "Lake Havasu City",
    "Casa Grande",
    "Sierra Vista",
    "Maricopa",
    "Oro Valley",
    "Prescott",
    "Bullhead City",
    "Prescott Valley",
    "Marana",
    "Apache Junction",
    "Jacksonville",
    "Miami",
    "Tampa",
    "Orlando",
    "St. Petersburg",
    "Hialeah",
    "Tallahassee",
    "Fort Lauderdale",
    "Port St. Lucie",
    "Cape Coral",
    "Pembroke Pines",
    "Hollywood",
    "Miramar",
    "Gainesville",
    "Coral Springs",
    "Miami Gardens",
    "Clearwater",
    "Palm Bay",
    "Pompano Beach",
    "West Palm Beach",
    "Lakeland",
    "Davie",
    "Miami Beach",
    "Sunrise",
    "Plantation",
    "Boca Raton",
    "Deltona",
    "Largo",
    "Deerfield Beach",
    "Palm Coast",
    "Melbourne",
    "Boynton Beach",
    "Lauderhill",
    "Weston",
    "Fort Myers",
    "Kissimmee",
    "Homestead",
    "Tamarac",
    "Delray Beach",
    "Daytona Beach",
    "North Miami",
    "Wellington",
    "North Port",
    "Jupiter",
    "Ocala",
    "Port Orange",
    "Margate",
    "Coconut Creek",
    "Sanford",
    "Sarasota",
    "Pensacola",
    "Bradenton",
    "Palm Beach Gardens",
    "Pinellas Park",
    "Coral Gables",
    "Doral",
    "Bonita Springs",
    "Apopka",
    "Titusville",
    "North Miami Beach",
    "Oakland Park",
    "Fort Pierce",
    "North Lauderdale",
    "Cutler Bay",
    "Altamonte Springs",
    "St. Cloud",
    "Greenacres",
    "Ormond Beach",
    "Ocoee",
    "Hallandale Beach",
    "Winter Garden",
    "Aventura",
    "Indianapolis",
    "Fort Wayne",
    "Evansville",
    "South Bend",
    "Carmel",
    "Bloomington",
    "Fishers",
    "Hammond",
    "Gary",
    "Muncie",
    "Lafayette",
    "Terre Haute",
    "Kokomo",
    "Anderson",
    "Noblesville",
    "Greenwood",
    "Elkhart",
    "Mishawaka",
    "Lawrence",
    "Jeffersonville",
    "Columbus",
    "Portage",
    "Columbus",
    "Cleveland",
    "Cincinnati",
    "Toledo",
    "Akron",
    "Dayton",
    "Parma",
    "Canton",
    "Youngstown",
    "Lorain",
    "Hamilton",
    "Springfield",
    "Kettering",
    "Elyria",
    "Lakewood",
    "Cuyahoga Falls",
    "Middletown",
    "Euclid",
    "Newark",
    "Mansfield",
    "Mentor",
    "Beavercreek",
    "Cleveland Heights",
    "Strongsville",
    "Dublin",
    "Fairfield",
    "Findlay",
    "Warren",
    "Lancaster",
    "Lima",
    "Huber Heights",
    "Westerville",
    "Marion",
    "Grove City",
    "Charlotte",
    "Raleigh",
    "Greensboro",
    "Durham",
    "Winston-Salem",
    "Fayetteville",
    "Cary",
    "Wilmington",
    "High Point",
    "Greenville",
    "Asheville",
    "Concord",
    "Gastonia",
    "Jacksonville",
    "Chapel Hill",
    "Rocky Mount",
    "Burlington",
    "Wilson",
    "Huntersville",
    "Kannapolis",
    "Apex",
    "Hickory",
    "Goldsboro",
    "Detroit",
    "Grand Rapids",
    "Warren",
    "Sterling Heights",
    "Ann Arbor",
    "Lansing",
    "Flint",
    "Dearborn",
    "Livonia",
    "Westland",
    "Troy",
    "Farmington Hills",
    "Kalamazoo",
    "Wyoming",
    "Southfield",
    "Rochester Hills",
    "Taylor",
    "Pontiac",
    "St. Clair Shores",
    "Royal Oak",
    "Novi",
    "Dearborn Heights",
    "Battle Creek",
    "Saginaw",
    "Kentwood",
    "East Lansing",
    "Roseville",
    "Portage",
    "Midland",
    "Lincoln Park",
    "Muskegon",
    "Memphis",
    "Nashville-Davidson",
    "Knoxville",
    "Chattanooga",
    "Clarksville",
    "Murfreesboro",
    "Jackson",
    "Franklin",
    "Johnson City",
    "Bartlett",
    "Hendersonville",
    "Kingsport",
    "Collierville",
    "Cleveland",
    "Smyrna",
    "Germantown",
    "Brentwood",
    "Boston",
    "Worcester",
    "Springfield",
    "Lowell",
    "Cambridge",
    "New Bedford",
    "Brockton",
    "Quincy",
    "Lynn",
    "Fall River",
    "Newton",
    "Lawrence",
    "Somerville",
    "Waltham",
    "Haverhill",
    "Malden",
    "Medford",
    "Taunton",
    "Chicopee",
    "Weymouth Town",
    "Revere",
    "Peabody",
    "Methuen",
    "Barnstable Town",
    "Pittsfield",
    "Attleboro",
    "Everett",
    "Salem",
    "Westfield",
    "Leominster",
    "Fitchburg",
    "Beverly",
    "Holyoke",
    "Marlborough",
    "Woburn",
    "Chelsea",
    "Seattle",
    "Spokane",
    "Tacoma",
    "Vancouver",
    "Bellevue",
    "Kent",
    "Everett",
    "Renton",
    "Yakima",
    "Federal Way",
    "Spokane Valley",
    "Bellingham",
    "Kennewick",
    "Auburn",
    "Pasco",
    "Marysville",
    "Lakewood",
    "Redmond",
    "Shoreline",
    "Richland",
    "Kirkland",
    "Burien",
    "Sammamish",
    "Olympia",
    "Lacey",
    "Edmonds",
    "Bremerton",
    "Puyallup",
    "Denver",
    "Colorado Springs",
    "Aurora",
    "Fort Collins",
    "Lakewood",
    "Thornton",
    "Arvada",
    "Westminster",
    "Pueblo",
    "Centennial",
    "Boulder",
    "Greeley",
    "Longmont",
    "Loveland",
    "Grand Junction",
    "Broomfield",
    "Castle Rock",
    "Commerce City",
    "Parker",
    "Littleton",
    "Northglenn",
    "Washington",
    "Baltimore",
    "Frederick",
    "Rockville",
    "Gaithersburg",
    "Bowie",
    "Hagerstown",
    "Annapolis",
    "Louisville/Jefferson County",
    "Lexington-Fayette",
    "Bowling Green",
    "Owensboro",
    "Covington",
    "Portland",
    "Eugene",
    "Salem",
    "Gresham",
    "Hillsboro",
    "Beaverton",
    "Bend",
    "Medford",
    "Springfield",
    "Corvallis",
    "Albany",
    "Tigard",
    "Lake Oswego",
    "Keizer",
    "Oklahoma City",
    "Tulsa",
    "Norman",
    "Broken Arrow",
    "Lawton",
    "Edmond",
    "Moore",
    "Midwest City",
    "Enid",
    "Stillwater",
    "Muskogee",
    "Milwaukee",
    "Madison",
    "Green Bay",
    "Kenosha",
    "Racine",
    "Appleton",
    "Waukesha",
    "Eau Claire",
    "Oshkosh",
    "Janesville",
    "West Allis",
    "La Crosse",
    "Sheboygan",
    "Wauwatosa",
    "Fond du Lac",
    "New Berlin",
    "Wausau",
    "Brookfield",
    "Greenfield",
    "Beloit",
    "Las Vegas",
    "Henderson",
    "Reno",
    "North Las Vegas",
    "Sparks",
    "Carson City",
    "Albuquerque",
    "Las Cruces",
    "Rio Rancho",
    "Santa Fe",
    "Roswell",
    "Farmington",
    "Clovis",
    "Kansas City",
    "St. Louis",
    "Springfield",
    "Independence",
    "Columbia",
    "Lee's Summit",
    "O'Fallon",
    "St. Joseph",
    "St. Charles",
    "St. Peters",
    "Blue Springs",
    "Florissant",
    "Joplin",
    "Chesterfield",
    "Jefferson City",
    "Cape Girardeau",
    "Virginia Beach",
    "Norfolk",
    "Chesapeake",
    "Richmond",
    "Newport News",
    "Alexandria",
    "Hampton",
    "Roanoke",
    "Portsmouth",
    "Suffolk",
    "Lynchburg",
    "Harrisonburg",
    "Leesburg",
    "Charlottesville",
    "Danville",
    "Blacksburg",
    "Manassas",
    "Atlanta",
    "Columbus",
    "Augusta-Richmond County",
    "Savannah",
    "Athens-Clarke County",
    "Sandy Springs",
    "Roswell",
    "Macon",
    "Johns Creek",
    "Albany",
    "Warner Robins",
    "Alpharetta",
    "Marietta",
    "Valdosta",
    "Smyrna",
    "Dunwoody",
    "Omaha",
    "Lincoln",
    "Bellevue",
    "Grand Island",
    "Minneapolis",
    "St. Paul",
    "Rochester",
    "Duluth",
    "Bloomington",
    "Brooklyn Park",
    "Plymouth",
    "St. Cloud",
    "Eagan",
    "Woodbury",
    "Maple Grove",
    "Eden Prairie",
    "Coon Rapids",
    "Burnsville",
    "Blaine",
    "Lakeville",
    "Minnetonka",
    "Apple Valley",
    "Edina",
    "St. Louis Park",
    "Mankato",
    "Maplewood",
    "Moorhead",
    "Shakopee",
    "Wichita",
    "Overland Park",
    "Kansas City",
    "Olathe",
    "Topeka",
    "Lawrence",
    "Shawnee",
    "Manhattan",
    "Lenexa",
    "Salina",
    "Hutchinson",
    "New Orleans",
    "Baton Rouge",
    "Shreveport",
    "Lafayette",
    "Lake Charles",
    "Kenner",
    "Bossier City",
    "Monroe",
    "Alexandria",
    "Honolulu",
    "Anchorage",
    "Newark",
    "Jersey City",
    "Paterson",
    "Elizabeth",
    "Clifton",
    "Trenton",
    "Camden",
    "Passaic",
    "Union City",
    "Bayonne",
    "East Orange",
    "Vineland",
    "New Brunswick",
    "Hoboken"
  )

}
